name: urssi-summer-school-2024-packaging
channels:
  - conda-forge
dependencies:
  - python=3.12
  - scipy >=1.6.0
  - cmake >=3.15
  - pytest >=7.0.0
  - jupytext >=1.16.0
  - pip
  - pip:
    - build >=1.1.0
